/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed3;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *entry1n;
  GtkWidget *entry2n;
  GtkWidget *entry3n;
  GtkObject *spinbutton1n_adj;
  GtkWidget *spinbutton1n;
  GtkWidget *button2n;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label8;
  GtkWidget *ajouter;
  GtkWidget *fixed2;
  GtkWidget *scrolledwindow1n;
  GtkWidget *treeview1n;
  GtkWidget *button1n;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *label9n;
  GtkWidget *entry100n;
  GtkWidget *label101n;
  GtkWidget *entry101n;
  GtkWidget *label11n;
  GtkWidget *entry102n;
  GtkObject *spinbutton11n_adj;
  GtkWidget *spinbutton11n;
  GtkWidget *label12n;
  GtkWidget *button100n;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label10;
  GtkWidget *afficher;
  GtkWidget *fixed4;
  GtkWidget *label9;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 1080, 664);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  label3 = gtk_label_new (_("destination:"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed3), label3, 16, 80);
  gtk_widget_set_size_request (label3, 152, 25);

  label4 = gtk_label_new (_("id:"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 64, 24);
  gtk_widget_set_size_request (label4, 41, 17);

  label5 = gtk_label_new (_("programme:"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 16, 136);
  gtk_widget_set_size_request (label5, 136, 17);

  label6 = gtk_label_new (_("nbre de place :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 24, 192);
  gtk_widget_set_size_request (label6, 128, 17);

  entry1n = gtk_entry_new ();
  gtk_widget_show (entry1n);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1n, 144, 24);
  gtk_widget_set_size_request (entry1n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1n), 8226);

  entry2n = gtk_entry_new ();
  gtk_widget_show (entry2n);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2n, 152, 72);
  gtk_widget_set_size_request (entry2n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2n), 8226);

  entry3n = gtk_entry_new ();
  gtk_widget_show (entry3n);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3n, 152, 128);
  gtk_widget_set_size_request (entry3n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3n), 8226);

  spinbutton1n_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1n_adj), 1, 0);
  gtk_widget_show (spinbutton1n);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1n, 152, 184);
  gtk_widget_set_size_request (spinbutton1n, 60, 27);

  button2n = gtk_button_new ();
  gtk_widget_show (button2n);
  gtk_fixed_put (GTK_FIXED (fixed3), button2n, 184, 272);
  gtk_widget_set_size_request (button2n, 68, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2n), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox2), label8, FALSE, FALSE, 0);

  ajouter = gtk_label_new (_("ajouter"));
  gtk_widget_show (ajouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), ajouter);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  scrolledwindow1n = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1n);
  gtk_fixed_put (GTK_FIXED (fixed2), scrolledwindow1n, 117, 61);
  gtk_widget_set_size_request (scrolledwindow1n, 700, 300);

  treeview1n = gtk_tree_view_new ();
  gtk_widget_show (treeview1n);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1n), treeview1n);

  button1n = gtk_button_new ();
  gtk_widget_show (button1n);
  gtk_fixed_put (GTK_FIXED (fixed2), button1n, 248, 16);
  gtk_widget_set_size_request (button1n, 68, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1n), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("button1"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);

  label9n = gtk_label_new (_("id:"));
  gtk_widget_show (label9n);
  gtk_fixed_put (GTK_FIXED (fixed2), label9n, 96, 400);
  gtk_widget_set_size_request (label9n, 41, 17);

  entry100n = gtk_entry_new ();
  gtk_widget_show (entry100n);
  gtk_fixed_put (GTK_FIXED (fixed2), entry100n, 144, 392);
  gtk_widget_set_size_request (entry100n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry100n), 8226);

  label101n = gtk_label_new (_("description"));
  gtk_widget_show (label101n);
  gtk_fixed_put (GTK_FIXED (fixed2), label101n, 352, 392);
  gtk_widget_set_size_request (label101n, 112, 25);

  entry101n = gtk_entry_new ();
  gtk_widget_show (entry101n);
  gtk_fixed_put (GTK_FIXED (fixed2), entry101n, 488, 392);
  gtk_widget_set_size_request (entry101n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry101n), 8226);

  label11n = gtk_label_new (_("programme:"));
  gtk_widget_show (label11n);
  gtk_fixed_put (GTK_FIXED (fixed2), label11n, 104, 448);
  gtk_widget_set_size_request (label11n, 144, 25);

  entry102n = gtk_entry_new ();
  gtk_widget_show (entry102n);
  gtk_fixed_put (GTK_FIXED (fixed2), entry102n, 304, 440);
  gtk_widget_set_size_request (entry102n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry102n), 8226);

  spinbutton11n_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton11n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11n_adj), 1, 0);
  gtk_widget_show (spinbutton11n);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton11n, 288, 504);
  gtk_widget_set_size_request (spinbutton11n, 60, 27);

  label12n = gtk_label_new (_("nbre des places disponible"));
  gtk_widget_show (label12n);
  gtk_fixed_put (GTK_FIXED (fixed2), label12n, 48, 504);
  gtk_widget_set_size_request (label12n, 208, 25);

  button100n = gtk_button_new ();
  gtk_widget_show (button100n);
  gtk_fixed_put (GTK_FIXED (fixed2), button100n, 280, 560);
  gtk_widget_set_size_request (button100n, 152, 37);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button100n), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox3), label10, FALSE, FALSE, 0);

  afficher = gtk_label_new (_("afficher"));
  gtk_widget_show (afficher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), afficher);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  label9 = gtk_label_new (_("label9"));
  gtk_widget_show (label9);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label9);

  g_signal_connect ((gpointer) button2n, "clicked",
                    G_CALLBACK (on_button2n_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1n, "row_activated",
                    G_CALLBACK (on_treeview1n_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1n, "clicked",
                    G_CALLBACK (on_button1n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button100n, "clicked",
                    G_CALLBACK (on_button100n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, entry1n, "entry1n");
  GLADE_HOOKUP_OBJECT (window1, entry2n, "entry2n");
  GLADE_HOOKUP_OBJECT (window1, entry3n, "entry3n");
  GLADE_HOOKUP_OBJECT (window1, spinbutton1n, "spinbutton1n");
  GLADE_HOOKUP_OBJECT (window1, button2n, "button2n");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1n, "scrolledwindow1n");
  GLADE_HOOKUP_OBJECT (window1, treeview1n, "treeview1n");
  GLADE_HOOKUP_OBJECT (window1, button1n, "button1n");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, label9n, "label9n");
  GLADE_HOOKUP_OBJECT (window1, entry100n, "entry100n");
  GLADE_HOOKUP_OBJECT (window1, label101n, "label101n");
  GLADE_HOOKUP_OBJECT (window1, entry101n, "entry101n");
  GLADE_HOOKUP_OBJECT (window1, label11n, "label11n");
  GLADE_HOOKUP_OBJECT (window1, entry102n, "entry102n");
  GLADE_HOOKUP_OBJECT (window1, spinbutton11n, "spinbutton11n");
  GLADE_HOOKUP_OBJECT (window1, label12n, "label12n");
  GLADE_HOOKUP_OBJECT (window1, button100n, "button100n");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed5;
  GtkWidget *label14;
  GtkWidget *label13;
  GtkWidget *label12;
  GtkWidget *label11;
  GtkWidget *entry122n;
  GtkWidget *entry123n;
  GtkWidget *entry124n;
  GtkObject *spinbutton120n_adj;
  GtkWidget *spinbutton120n;
  GtkWidget *button119n;
  GtkWidget *button120n;
  GtkWidget *button121n;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label15;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window2), fixed5);

  label14 = gtk_label_new (_("nbre de place:"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed5), label14, 0, 200);
  gtk_widget_set_size_request (label14, 144, 17);

  label13 = gtk_label_new (_("programme:"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed5), label13, 8, 144);
  gtk_widget_set_size_request (label13, 128, 17);

  label12 = gtk_label_new (_("description:"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed5), label12, 8, 88);
  gtk_widget_set_size_request (label12, 112, 25);

  label11 = gtk_label_new (_("identifiant:"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed5), label11, 0, 56);
  gtk_widget_set_size_request (label11, 128, 16);

  entry122n = gtk_entry_new ();
  gtk_widget_show (entry122n);
  gtk_fixed_put (GTK_FIXED (fixed5), entry122n, 152, 48);
  gtk_widget_set_size_request (entry122n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry122n), 8226);

  entry123n = gtk_entry_new ();
  gtk_widget_show (entry123n);
  gtk_fixed_put (GTK_FIXED (fixed5), entry123n, 136, 88);
  gtk_widget_set_size_request (entry123n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry123n), 8226);

  entry124n = gtk_entry_new ();
  gtk_widget_show (entry124n);
  gtk_fixed_put (GTK_FIXED (fixed5), entry124n, 144, 144);
  gtk_widget_set_size_request (entry124n, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry124n), 8226);

  spinbutton120n_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton120n = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton120n_adj), 1, 0);
  gtk_widget_show (spinbutton120n);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton120n, 144, 200);
  gtk_widget_set_size_request (spinbutton120n, 60, 27);

  button119n = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (button119n);
  gtk_fixed_put (GTK_FIXED (fixed5), button119n, 24, 256);
  gtk_widget_set_size_request (button119n, 68, 29);

  button120n = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (button120n);
  gtk_fixed_put (GTK_FIXED (fixed5), button120n, 152, 256);
  gtk_widget_set_size_request (button120n, 68, 29);

  button121n = gtk_button_new ();
  gtk_widget_show (button121n);
  gtk_fixed_put (GTK_FIXED (fixed5), button121n, 248, 256);
  gtk_widget_set_size_request (button121n, 68, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button121n), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox4), label15, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button119n, "clicked",
                    G_CALLBACK (on_button119n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button120n, "clicked",
                    G_CALLBACK (on_button120n_clicked),
                    NULL);
  g_signal_connect ((gpointer) button121n, "clicked",
                    G_CALLBACK (on_button121n_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window2, label14, "label14");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2, label11, "label11");
  GLADE_HOOKUP_OBJECT (window2, entry122n, "entry122n");
  GLADE_HOOKUP_OBJECT (window2, entry123n, "entry123n");
  GLADE_HOOKUP_OBJECT (window2, entry124n, "entry124n");
  GLADE_HOOKUP_OBJECT (window2, spinbutton120n, "spinbutton120n");
  GLADE_HOOKUP_OBJECT (window2, button119n, "button119n");
  GLADE_HOOKUP_OBJECT (window2, button120n, "button120n");
  GLADE_HOOKUP_OBJECT (window2, button121n, "button121n");
  GLADE_HOOKUP_OBJECT (window2, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window2, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window2, image4, "image4");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");

  return window2;
}

