/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_aceuil (void);
GtkWidget* create_client (void);
GtkWidget* create_agent (void);
GtkWidget* create_ajouexcu (void);
GtkWidget* create_modifexcu (void);
GtkWidget* create_ajouhotel (void);
GtkWidget* create_modifhotel (void);
GtkWidget* create_ajouvol (void);
GtkWidget* create_modifvol (void);
GtkWidget* create_admin (void);
GtkWidget* create_ajoutcompt (void);
GtkWidget* create_window3 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_modresv (void);
GtkWidget* create_modresh (void);
GtkWidget* create_modrese (void);
GtkWidget* create_window2h (void);
GtkWidget* create_windowhad (void);
GtkWidget* create_windowhag (void);
GtkWidget* create_modcompt (void);
