/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *aceuil;
  GtkWidget *client;
  GtkWidget *agent;
  GtkWidget *ajouexcu;
  GtkWidget *modifexcu;
  GtkWidget *ajouhotel;
  GtkWidget *modifhotel;
  GtkWidget *ajouvol;
  GtkWidget *modifvol;
  GtkWidget *admin;
  GtkWidget *ajoutcompt;
  //GtkWidget *window3;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  aceuil = create_aceuil ();
  gtk_widget_show (aceuil);
 /* client = create_client ();
  gtk_widget_show (client);
  agent = create_agent ();
  gtk_widget_show (agent);
  ajouexcu = create_ajouexcu ();
  gtk_widget_show (ajouexcu);
  modifexcu = create_modifexcu ();
  gtk_widget_show (modifexcu);
  ajouhotel = create_ajouhotel ();
  gtk_widget_show (ajouhotel);
  modifhotel = create_modifhotel ();
  gtk_widget_show (modifhotel);
  ajouvol = create_ajouvol ();
  gtk_widget_show (ajouvol);
  modifvol = create_modifvol ();
  gtk_widget_show (modifvol);
  admin = create_admin ();
  gtk_widget_show (admin);
  ajoutcompt = create_ajoutcompt ();
  gtk_widget_show (ajoutcompt);*/

  gtk_main ();
  return 0;
}

